### ISSUE TITLE
Service trait required?

### ISSUE THREAD

**Issue by ProjectMoon** [titanous/grpc-web-client#1]
So as you probably know from https://github.com/hyperium/tonic/issues/645, I am trying to use this well before it's integrated into Tonic! I have tried integrating it into a simple Yew application without success so far. I'm reporting this because maybe it's relevant to your PR.

I get this error when even just writing an async fn for calling a test endpoint, without calling it:

```
the trait `Service<yew::services::fetch::Request<http_body::combinators::box_body::BoxBody<bytes::bytes::Bytes, Status>>>` is not implemented for `Client`
```

`yew::services::fetch::Request` is a re-exported `http::Request`. But I have no idea what `Service` is or where it comes from. One person guessed tokio-tower. I tried disabling the `services` feature of Yew, too. The error still occurs.

**Comment by titanous** [comment]
Can you post an example repo that isolates the issue? This will be helpful to test with, so far I only have tested with Seed, which doesn't export `Request`.

**Comment by ProjectMoon** [comment]
I have it in a local repository now, tightly woven together with other stuff. I'll try to isolate it and upload something.

**Comment by ProjectMoon** [comment]
Here is the self-contained example: https://git.agnos.is/projectmoon/service-trait-example

If you clone it and run `yarn run webpack` (after running `yarn install` to download all the dependencies), it should attempt to build everything, but fail during crate compilation because of the error mentioned in the issue.

**Comment by robert-chiniquy** [comment]
Hi! I've hit this same issue while trying to do essentially the same thing. I would really love to make this work. Is there a way forward, with that branch having been deleted? Is there a revision of tonic to check out which will make this build? 

Otherwise, looking forward to the PR mentioned here: https://github.com/hyperium/tonic/issues/645#issuecomment-853947361 This would be a fantastic capability for tonic to have.

**Comment by tharvik** [comment]
Same issue here, but I found a fix :)

The [`Service`](https://docs.rs/tower-service/0.3.1/tower_service/trait.Service.html) trait is required for the blanket implementation of [`GrpcService`](https://docs.rs/tonic/0.5.2/tonic/client/trait.GrpcService.html). As `grpc-web-client` was implemented with an older incompatible version, it fails to match the two. Bumping the deps of `grpc-web-client` fixes that.

You can see (and comment/contribute) to the PR fixing it: https://github.com/titanous/grpc-web-client/pull/4.
