### ISSUE TITLE
Looks like library needs to be updated to work with tonic 0.6

### ISSUE THREAD

**Issue by andoriyu** [titanous/grpc-web-client#7]
tonic recently changed response's body to `UnsyncBody` i guess that creates a lot of issues for this library.

**Comment by tharvik** [comment]
Simply [bumping the deps](https://github.com/titanous/grpc-web-client/pull/8) seems to work.

**Comment by andoriyu** [comment]
Weird, I tried bumping dependencies, but it was still failing for me. I think I didn't bump `wasm-streams`. Thanks for updating it.
